# GitHub Pages workflow code

name: GitHub Pages # ==========================================================

on:
  push:
    branches: [ main ]
    paths:
      - "docs/website/**"
      - ".github/workflows/gh-pages.yml"
      - "!README.md" # don't rebuild on documentation changes
  pull_request:

jobs: # =======================================================================

  # ---------------------------------------------------------------------------
  deploy: # deploy the Hugo website we are using for documentation
  # ---------------------------------------------------------------------------
    runs-on: ubuntu-latest # [self-hosted, ubuntu-20.04]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    permissions:
      contents: write  # needed to push to gh-pages branch
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.1
        # with:
        #   submodules: recursive  # Fetch Hugo themes (true OR recursive)
        #   fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Update themes used by the website
        run: |
          git submodule update --init docs/website/themes/hugo-notice
          git submodule update --init docs/website/themes/hugo-cite
          git submodule update --init docs/website/themes/book

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@6e295a6a0c9087bf374299e9d67f9d2edab9f18f # v3.0.0
        with:
          hugo-version: '0.159.1'
          extended: true

      - name: Build
        run: |
          cd docs/website
          hugo --minify
          cd ../..

      - name: Deploy
        uses: peaceiris/actions-gh-pages@4a2e02b36f31d8974a0d09d3bb9f3172aa2d0d0d # v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/website/public
          publish_branch: gh-pages
